import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Grid } from "./_components/Grid";
const inter = Inter({ subsets: ["latin"] });
import { Suspense } from "react";
import Home from "./page";

export const metadata: Metadata = {
  title: "Quasar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-[100vh]">
        <Suspense fallback={<p>loading.....</p>}>
          <Grid components={<Home />} />
        </Suspense>
      </body>
    </html>
  );
}
