import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Grid } from "./_common/Grid";
const inter = Inter({ subsets: ["latin"] });
import Home from "./page";

export const metadata: Metadata = {
  title: "Quasar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-[100vh]">
        <Grid components={<Home />} />
      </body>
    </html>
  );
}
